### PR TITLE
Addpmdata 0.0.6

### PR DESCRIPTION
**Pull request by erikarasnick**

### CODE REVIEW

**Comment by erikarasnick** [comment]
@cole-brokamp you should be able to pull down the test container

`ghcr.io/degauss-org/pm:addpmdata-0.0.6`

**Comment by cole-brokamp** [comment]
It is amazing to look at the actions and see the logs of it being built and being tested.  I'm not even sure if pulling it would be necessary once it passes the checks.  

Either way, I immediately got an unauthorized error when I first tried a `docker pull ghcr.io/degauss-org/pm:addpmdata-0.0.6`. 

The package settings say that we have "inherited access" enabled and the corresponding repo's access settings are set to public, so I figure that wouldn't be the issue.  I unchecked "inherited access" and added myself as an admin, but I still get the same unauthorized error.

I am getting unauthorized for trying to pull any version of the pm container from ghcr.io.  Is there something else that we need to change to make the containers publicly available?  I might be able to get some credentials for ghcr.io, but I want to keep them all public anyway.

(By the way, what is the "latest" tag, does that get pushed along with the PR title version?  It seems like we should force this to point to the latest released version instead.)

**Comment by erikarasnick** [comment]
I just changed visibility to public under package settings. Try it now? 

I agree. I will look into forcing 'latest' to be the same as the latest release version.

**Comment by cole-brokamp** [comment]
pull is working for me now; go ahead and merge this PR, then create a release and make sure its all working as expected.

**Pull request merged**
